---
# Install golang and configure development environment (https://golang.org)
- name: Download Golang tarball
  get_url:
    url: "{{ golang_release }}"
    dest: "/tmp/{{ golang_download_file }}"

- name: Clean current install
  file: path="/usr/local/go/" state=absent

- name: Extract Golang tarball
  raw: "tar -C /usr/local -xzf /tmp/{{ golang_download_file }}"

- name: Create go workspace directory
  file: path="{{ ansible_env.HOME }}/Development/go" state=directory

- name: Create environment variables
  lineinfile: dest="{{ ansible_env.HOME }}/.config/fish/config.fish" line={{ item.line }}
  with_items:
    - { line: 'set -x GOROOT /usr/local/go'}
    - { line: 'set -x GOPATH $HOME/Development/go'}
    - { line: 'set -x PATH $PATH $GOROOT/bin/ $GOPATH/bin'}

- name: Remove tarball
  file: path="/tmp/{{ golang_download_file }}" state=absent