---
# Install golang and configure development environment (https://golang.org)

- name: Downoad Golang tarball
  become: yes
  get_url:
    url: "https://storage.googleapis.com/golang/go{{ golang_version }}.darwin-amd64.tar.gz"
    dest: "/tmp/go{{ golang_version }}.darwin-amd64.tar.gz"

- name: Extract Golang tarball
  become: yes
  raw: "tar -C /usr/local -xzf /tmp/go{{ golang_version }}.darwin-amd64.tar.gz"

- name: Create go workspace directory
  file: path="{{ ansible_env.HOME }}/Development/go" state=directory