---
# Install golang and configure development environment (https://golang.org)

- name: Download Golang tarball
  become: yes
  get_url:
    url: "https://storage.googleapis.com/golang/go{{ golang_version }}.darwin-amd64.tar.gz"
    dest: "/tmp/go{{ golang_version }}.darwin-amd64.tar.gz"

- name: Extract Golang tarball
  become: yes
  raw: "tar -C /usr/local -xzf /tmp/go{{ golang_version }}.darwin-amd64.tar.gz"

- name: Create go workspace directory
  file: path="{{ ansible_env.HOME }}/Development/go" state=directory

- name: Create environment variables
  lineinfile: dest="{{ ansible_env.HOME }}/.config/fish/config.fish" line={{ item.line }}
  with_items:
    - { line: 'set -x GOROOT /usr/local/go'}
    - { line: 'set -x GOPATH $HOME/Development/go'}
    - { line: 'set -x PATH $PATH $GOROOT/bin/ $GOPATH/bin'}

- name: Remove tarball
  become: yes
  file: path=/tmp/go{{ golang_version }}.darwin-amd64.tar.gz state=absent