---
# Install fish interactive shell (https://fishshell.com)

- name: Install fish terminal
  homebrew: name=fish state=latest

- name: Add Fish to /etc/shells
  lineinfile: dest=/etc/shells line='/usr/local/bin/fish'
  become: yes

- name: Make Fish your default shell
  raw: chsh -s /usr/local/bin/fish
  become: yes

- name: Create fish config file
  file: path="{{ ansible_env.HOME }}/.config/fish/config.fish" state=touch